name: arduino-lint
on:
  push:
    paths:
      - "library.properties"
      - ".github/workflows/arduino-lint.yml"
      - "src/**"
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Arduino Lint (Library Manager update mode)
        uses: arduino/arduino-lint-action@v1
        with:
          compliance: specification
          project-type: library
          library-manager: update