name: arduino-lint
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/arduino-lint-action@v1
        with:
          compliance: strict
          project-type: library
          library-manager: update   # repo URL ve maintainer email doğru olmalı